export const DEVICE_COMPATIBILITY = ["mobile", "tablet", "desktop"];

export const FLUENT_LANGUAGE_INDEX_PROLIFIC_MAPPING = {
  "Rather not say": {
    label: "Rather not say",
    name: "Rather not say",
    value: false,
    index: 0,
  },
  Afrikaans: {
    label: "Afrikaans",
    name: "Afrikaans",
    value: true,
    index: 1,
  },
  Albanian: {
    label: "Albanian",
    name: "Albanian",
    value: true,
    index: 2,
  },
  Amharic: {
    label: "Amharic",
    name: "Amharic",
    value: true,
    index: 3,
  },
  Arabic: {
    label: "Arabic",
    name: "Arabic",
    value: true,
    index: 4,
  },
  Armenian: {
    label: "Armenian",
    name: "Armenian",
    value: true,
    index: 5,
  },
  Basque: {
    label: "Basque",
    name: "Basque",
    value: true,
    index: 6,
  },
  Bengali: {
    label: "Bengali",
    name: "Bengali",
    value: true,
    index: 7,
  },
  Belarusian: {
    label: "Belarusian",
    name: "Belarusian",
    value: true,
    index: 8,
  },
  Burmese: {
    label: "Burmese",
    name: "Burmese",
    value: true,
    index: 9,
  },
  Bulgarian: {
    label: "Bulgarian",
    name: "Bulgarian",
    value: true,
    index: 10,
  },
  Catalan: {
    label: "Catalan",
    name: "Catalan",
    value: true,
    index: 11,
  },
  Czech: {
    label: "Czech",
    name: "Czech",
    value: true,
    index: 12,
  },
  Chinese: {
    label: "Chinese",
    name: "Chinese",
    value: true,
    index: 13,
  },
  Croatian: {
    label: "Croatian",
    name: "Croatian",
    value: true,
    index: 14,
  },
  Danish: {
    label: "Danish",
    name: "Danish",
    value: true,
    index: 15,
  },
  Dari: {
    label: "Dari",
    name: "Dari",
    value: true,
    index: 16,
  },
  Dzongkha: {
    label: "Dzongkha",
    name: "Dzongkha",
    value: true,
    index: 17,
  },
  Dutch: {
    label: "Dutch",
    name: "Dutch",
    value: true,
    index: 18,
  },
  English: {
    label: "English",
    name: "English",
    value: true,
    index: 19,
  },
  Esperanto: {
    label: "Esperanto",
    name: "Esperanto",
    value: true,
    index: 20,
  },
  Estonian: {
    label: "Estonian",
    name: "Estonian",
    value: true,
    index: 21,
  },
  Faroese: {
    label: "Faroese",
    name: "Faroese",
    value: true,
    index: 22,
  },
  Farsi: {
    label: "Farsi",
    name: "Farsi",
    value: true,
    index: 23,
  },
  Finnish: {
    label: "Finnish",
    name: "Finnish",
    value: true,
    index: 24,
  },
  French: {
    label: "French",
    name: "French",
    value: true,
    index: 25,
  },
  Gaelic: {
    label: "Gaelic",
    name: "Gaelic",
    value: true,
    index: 26,
  },
  Galician: {
    label: "Galician",
    name: "Galician",
    value: true,
    index: 27,
  },
  German: {
    label: "German",
    name: "German",
    value: true,
    index: 28,
  },
  Greek: {
    label: "Greek",
    name: "Greek",
    value: true,
    index: 29,
  },
  Hebrew: {
    label: "Hebrew",
    name: "Hebrew",
    value: true,
    index: 30,
  },
  Hindi: {
    label: "Hindi",
    name: "Hindi",
    value: true,
    index: 31,
  },
  Hungarian: {
    label: "Hungarian",
    name: "Hungarian",
    value: true,
    index: 32,
  },
  Icelandic: {
    label: "Icelandic",
    name: "Icelandic",
    value: true,
    index: 33,
  },
  Indonesian: {
    label: "Indonesian",
    name: "Indonesian",
    value: true,
    index: 34,
  },
  Inuktitut: {
    label: "Inuktitut",
    name: "Inuktitut",
    value: true,
    index: 35,
  },
  Italian: {
    label: "Italian",
    name: "Italian",
    value: true,
    index: 36,
  },
  Japanese: {
    label: "Japanese",
    name: "Japanese",
    value: true,
    index: 37,
  },
  Khmer: {
    label: "Khmer",
    name: "Khmer",
    value: true,
    index: 38,
  },
  Korean: {
    label: "Korean",
    name: "Korean",
    value: true,
    index: 39,
  },
  Kurdish: {
    label: "Kurdish",
    name: "Kurdish",
    value: true,
    index: 40,
  },
  Laotian: {
    label: "Laotian",
    name: "Laotian",
    value: true,
    index: 41,
  },
  Latvian: {
    label: "Latvian",
    name: "Latvian",
    value: true,
    index: 42,
  },
  Lappish: {
    label: "Lappish",
    name: "Lappish",
    value: true,
    index: 43,
  },
  Lithuanian: {
    label: "Lithuanian",
    name: "Lithuanian",
    value: true,
    index: 44,
  },
  Macedonian: {
    label: "Macedonian",
    name: "Macedonian",
    value: true,
    index: 45,
  },
  Malay: {
    label: "Malay",
    name: "Malay",
    value: true,
    index: 46,
  },
  Maltese: {
    label: "Maltese",
    name: "Maltese",
    value: true,
    index: 47,
  },
  Nepali: {
    label: "Nepali",
    name: "Nepali",
    value: true,
    index: 48,
  },
  Norwegian: {
    label: "Norwegian",
    name: "Norwegian",
    value: true,
    index: 49,
  },
  Pashto: {
    label: "Pashto",
    name: "Pashto",
    value: true,
    index: 50,
  },
  Polish: {
    label: "Polish",
    name: "Polish",
    value: true,
    index: 51,
  },
  Portuguese: {
    label: "Portuguese",
    name: "Portuguese",
    value: true,
    index: 52,
  },
  Romanian: {
    label: "Romanian",
    name: "Romanian",
    value: true,
    index: 53,
  },
  Russian: {
    label: "Russian",
    name: "Russian",
    value: true,
    index: 54,
  },
  Scots: {
    label: "Scots",
    name: "Scots",
    value: true,
    index: 55,
  },
  Serbian: {
    label: "Serbian",
    name: "Serbian",
    value: true,
    index: 56,
  },
  Slovak: {
    label: "Slovak",
    name: "Slovak",
    value: true,
    index: 57,
  },
  Slovenian: {
    label: "Slovenian",
    name: "Slovenian",
    value: true,
    index: 58,
  },
  Somali: {
    label: "Somali",
    name: "Somali",
    value: true,
    index: 59,
  },
  Spanish: {
    label: "Spanish",
    name: "Spanish",
    value: true,
    index: 60,
  },
  Swedish: {
    label: "Swedish",
    name: "Swedish",
    value: true,
    index: 61,
  },
  Swahili: {
    label: "Swahili",
    name: "Swahili",
    value: true,
    index: 62,
  },
  "Tagalog-Filipino": {
    label: "Tagalog-Filipino",
    name: "Tagalog-Filipino",
    value: true,
    index: 63,
  },
  Tajik: {
    label: "Tajik",
    name: "Tajik",
    value: true,
    index: 64,
  },
  Tamil: {
    label: "Tamil",
    name: "Tamil",
    value: true,
    index: 65,
  },
  Thai: {
    label: "Thai",
    name: "Thai",
    value: true,
    index: 66,
  },
  Tibetan: {
    label: "Tibetan",
    name: "Tibetan",
    value: true,
    index: 67,
  },
  Tigrinya: {
    label: "Tigrinya",
    name: "Tigrinya",
    value: true,
    index: 68,
  },
  Tongan: {
    label: "Tongan",
    name: "Tongan",
    value: true,
    index: 69,
  },
  Turkish: {
    label: "Turkish",
    name: "Turkish",
    value: true,
    index: 70,
  },
  Turkmen: {
    label: "Turkmen",
    name: "Turkmen",
    value: true,
    index: 71,
  },
  Ukrainian: {
    label: "Ukrainian",
    name: "Ukrainian",
    value: true,
    index: 72,
  },
  Urdu: {
    label: "Urdu",
    name: "Urdu",
    value: true,
    index: 73,
  },
  Uzbek: {
    label: "Uzbek",
    name: "Uzbek",
    value: true,
    index: 74,
  },
  Welsh: {
    label: "Welsh",
    name: "Welsh",
    value: true,
    index: 75,
  },
  Vietnamese: {
    label: "Vietnamese",
    name: "Vietnamese",
    value: true,
    index: 76,
  },
  Telugu: {
    label: "Telugu",
    name: "Telugu",
    value: true,
    index: 77,
  },
  Papiamento: {
    label: "Papiamento",
    name: "Papiamento",
    value: true,
    index: 78,
  },
  Twi: {
    label: "Twi",
    name: "Twi",
    value: true,
    index: 79,
  },
  Cantonese: {
    label: "Cantonese",
    name: "Cantonese",
    value: true,
    index: 80,
  },
  Mandarin: {
    label: "Mandarin",
    name: "Mandarin",
    value: true,
    index: 81,
  },
  Hakka: {
    label: "Hakka",
    name: "Hakka",
    value: true,
    index: 82,
  },
  Malayalam: {
    label: "Malayalam",
    name: "Malayalam",
    value: true,
    index: 83,
  },
  Gujarati: {
    label: "Gujarati",
    name: "Gujarati",
    value: true,
    index: 84,
  },
  Punjabi: {
    label: "Punjabi",
    name: "Punjabi",
    value: true,
    index: 85,
  },
  Other: {
    label: "Other",
    name: "Other",
    value: true,
    index: 86,
  },
};

export const LANGUAGE_INDEX_PROLIFIC_MAPPING = {
  Afrikaans: {
    label: "Afrikaans",
    name: "Afrikaans",
    value: false,
    index: 0,
  },
  Albanian: {
    label: "Albanian",
    name: "Albanian",
    value: false,
    index: 1,
  },
  Amharic: {
    label: "Amharic",
    name: "Amharic",
    value: false,
    index: 2,
  },
  Arabic: {
    label: "Arabic",
    name: "Arabic",
    value: false,
    index: 3,
  },
  Armenian: {
    label: "Armenian",
    name: "Armenian",
    value: false,
    index: 4,
  },
  Basque: {
    label: "Basque",
    name: "Basque",
    value: false,
    index: 5,
  },
  Bengali: {
    label: "Bengali",
    name: "Bengali",
    value: false,
    index: 6,
  },
  Belarusian: {
    label: "Belarusian",
    name: "Belarusian",
    value: false,
    index: 7,
  },
  Burmese: {
    label: "Burmese",
    name: "Burmese",
    value: false,
    index: 8,
  },
  Bulgarian: {
    label: "Bulgarian",
    name: "Bulgarian",
    value: false,
    index: 9,
  },
  Catalan: {
    label: "Catalan",
    name: "Catalan",
    value: false,
    index: 10,
  },
  Czech: {
    label: "Czech",
    name: "Czech",
    value: false,
    index: 11,
  },
  Chinese: {
    label: "Chinese",
    name: "Chinese",
    value: false,
    index: 12,
  },
  Croatian: {
    label: "Croatian",
    name: "Croatian",
    value: false,
    index: 13,
  },
  Danish: {
    label: "Danish",
    name: "Danish",
    value: false,
    index: 14,
  },
  Dari: {
    label: "Dari",
    name: "Dari",
    value: false,
    index: 15,
  },
  Dzongkha: {
    label: "Dzongkha",
    name: "Dzongkha",
    value: false,
    index: 16,
  },
  Dutch: {
    label: "Dutch",
    name: "Dutch",
    value: false,
    index: 17,
  },
  English: {
    label: "English",
    name: "English",
    value: false,
    index: 18,
  },
  Esperanto: {
    label: "Esperanto",
    name: "Esperanto",
    value: false,
    index: 19,
  },
  Estonian: {
    label: "Estonian",
    name: "Estonian",
    value: false,
    index: 20,
  },
  Faroese: {
    label: "Faroese",
    name: "Faroese",
    value: false,
    index: 21,
  },
  Farsi: {
    label: "Farsi",
    name: "Farsi",
    value: false,
    index: 22,
  },
  Finnish: {
    label: "Finnish",
    name: "Finnish",
    value: false,
    index: 23,
  },
  French: {
    label: "French",
    name: "French",
    value: false,
    index: 24,
  },
  Gaelic: {
    label: "Gaelic",
    name: "Gaelic",
    value: false,
    index: 25,
  },
  Galician: {
    label: "Galician",
    name: "Galician",
    value: false,
    index: 26,
  },
  German: {
    label: "German",
    name: "German",
    value: false,
    index: 27,
  },
  Greek: {
    label: "Greek",
    name: "Greek",
    value: false,
    index: 28,
  },
  Hebrew: {
    label: "Hebrew",
    name: "Hebrew",
    value: false,
    index: 29,
  },
  Hindi: {
    label: "Hindi",
    name: "Hindi",
    value: false,
    index: 30,
  },
  Hungarian: {
    label: "Hungarian",
    name: "Hungarian",
    value: false,
    index: 31,
  },
  Icelandic: {
    label: "Icelandic",
    name: "Icelandic",
    value: false,
    index: 32,
  },
  Indonesian: {
    label: "Indonesian",
    name: "Indonesian",
    value: false,
    index: 33,
  },
  Inuktitut: {
    label: "Inuktitut",
    name: "Inuktitut",
    value: false,
    index: 34,
  },
  Italian: {
    label: "Italian",
    name: "Italian",
    value: false,
    index: 35,
  },
  Japanese: {
    label: "Japanese",
    name: "Japanese",
    value: false,
    index: 36,
  },
  Khmer: {
    label: "Khmer",
    name: "Khmer",
    value: false,
    index: 37,
  },
  Korean: {
    label: "Korean",
    name: "Korean",
    value: false,
    index: 38,
  },
  Kurdish: {
    label: "Kurdish",
    name: "Kurdish",
    value: false,
    index: 39,
  },
  Laotian: {
    label: "Laotian",
    name: "Laotian",
    value: false,
    index: 40,
  },
  Latvian: {
    label: "Latvian",
    name: "Latvian",
    value: false,
    index: 41,
  },
  Lappish: {
    label: "Lappish",
    name: "Lappish",
    value: false,
    index: 42,
  },
  Lithuanian: {
    label: "Lithuanian",
    name: "Lithuanian",
    value: false,
    index: 43,
  },
  Macedonian: {
    label: "Macedonian",
    name: "Macedonian",
    value: false,
    index: 44,
  },
  Malay: {
    label: "Malay",
    name: "Malay",
    value: false,
    index: 45,
  },
  Maltese: {
    label: "Maltese",
    name: "Maltese",
    value: false,
    index: 46,
  },
  Nepali: {
    label: "Nepali",
    name: "Nepali",
    value: false,
    index: 47,
  },
  Norwegian: {
    label: "Norwegian",
    name: "Norwegian",
    value: false,
    index: 48,
  },
  Pashto: {
    label: "Pashto",
    name: "Pashto",
    value: false,
    index: 49,
  },
  Polish: {
    label: "Polish",
    name: "Polish",
    value: false,
    index: 50,
  },
  Portuguese: {
    label: "Portuguese",
    name: "Portuguese",
    value: false,
    index: 51,
  },
  Romanian: {
    label: "Romanian",
    name: "Romanian",
    value: false,
    index: 52,
  },
  Russian: {
    label: "Russian",
    name: "Russian",
    value: false,
    index: 53,
  },
  Scots: {
    label: "Scots",
    name: "Scots",
    value: false,
    index: 54,
  },
  Serbian: {
    label: "Serbian",
    name: "Serbian",
    value: false,
    index: 55,
  },
  Slovak: {
    label: "Slovak",
    name: "Slovak",
    value: false,
    index: 56,
  },
  Slovenian: {
    label: "Slovenian",
    name: "Slovenian",
    value: false,
    index: 57,
  },
  Somali: {
    label: "Somali",
    name: "Somali",
    value: false,
    index: 58,
  },
  Spanish: {
    label: "Spanish",
    name: "Spanish",
    value: false,
    index: 59,
  },
  Swedish: {
    label: "Swedish",
    name: "Swedish",
    value: false,
    index: 60,
  },
  Swahili: {
    label: "Swahili",
    name: "Swahili",
    value: false,
    index: 61,
  },
  "Tagalog-Filipino": {
    label: "Tagalog-Filipino",
    name: "Tagalog-Filipino",
    value: false,
    index: 62,
  },
  Tajik: {
    label: "Tajik",
    name: "Tajik",
    value: false,
    index: 63,
  },
  Tamil: {
    label: "Tamil",
    name: "Tamil",
    value: false,
    index: 64,
  },
  Thai: {
    label: "Thai",
    name: "Thai",
    value: false,
    index: 65,
  },
  Tibetan: {
    label: "Tibetan",
    name: "Tibetan",
    value: false,
    index: 66,
  },
  Tigrinya: {
    label: "Tigrinya",
    name: "Tigrinya",
    value: false,
    index: 67,
  },
  Tongan: {
    label: "Tongan",
    name: "Tongan",
    value: false,
    index: 68,
  },
  Turkish: {
    label: "Turkish",
    name: "Turkish",
    value: false,
    index: 69,
  },
  Turkmen: {
    label: "Turkmen",
    name: "Turkmen",
    value: false,
    index: 70,
  },
  Ukrainian: {
    label: "Ukrainian",
    name: "Ukrainian",
    value: false,
    index: 71,
  },
  Urdu: {
    label: "Urdu",
    name: "Urdu",
    value: false,
    index: 72,
  },
  Uzbek: {
    label: "Uzbek",
    name: "Uzbek",
    value: false,
    index: 73,
  },
  Welsh: {
    label: "Welsh",
    name: "Welsh",
    value: false,
    index: 74,
  },
  Vietnamese: {
    label: "Vietnamese",
    name: "Vietnamese",
    value: false,
    index: 75,
  },
  Telugu: {
    label: "Telugu",
    name: "Telugu",
    value: false,
    index: 76,
  },
  Papiamento: {
    label: "Papiamento",
    name: "Papiamento",
    value: false,
    index: 77,
  },
  Twi: {
    label: "Twi",
    name: "Twi",
    value: false,
    index: 78,
  },
  Cantonese: {
    label: "Cantonese",
    name: "Cantonese",
    value: false,
    index: 79,
  },
  Mandarin: {
    label: "Mandarin",
    name: "Mandarin",
    value: false,
    index: 80,
  },
  Hakka: {
    label: "Hakka",
    name: "Hakka",
    value: false,
    index: 81,
  },
  Malayalam: {
    label: "Malayalam",
    name: "Malayalam",
    value: false,
    index: 82,
  },
  Gujarati: {
    label: "Gujarati",
    name: "Gujarati",
    value: false,
    index: 83,
  },
  Punjabi: {
    label: "Punjabi",
    name: "Punjabi",
    value: false,
    index: 84,
  },
  Georgian: {
    label: "Georgian",
    name: "Georgian",
    value: false,
    index: 85,
  },
  Other: {
    label: "Other",
    name: "Other",
    value: false,
    index: 86,
  },
};

export const LOCATION_INDEX_PROLIFIC_MAPPING = {
  UK: {
    label: "United Kingdom",
    name: "United Kingdom",
    value: false,
    index: 0,
  },
  USA: {
    label: "United States",
    name: "United States",
    value: false,
    index: 1,
  },
  Ireland: {
    label: "Ireland",
    name: "Ireland",
    value: false,
    index: 2,
  },
  Germany: {
    label: "Germany",
    name: "Germany",
    value: true,
    index: 3,
  },
  France: {
    label: "France",
    name: "France",
    value: true,
    index: 4,
  },
  Spain: {
    label: "Spain",
    name: "Spain",
    value: false,
    index: 5,
  },
  Afghanistan: {
    label: "Afghanistan",
    name: "Afghanistan",
    value: false,
    index: 6,
  },
  "Aland Islands": {
    label: "Aland Islands",
    name: "Aland Islands",
    value: false,
    index: 7,
  },
  Albania: {
    label: "Albania",
    name: "Albania",
    value: false,
    index: 8,
  },
  Algeria: {
    label: "Algeria",
    name: "Algeria",
    value: false,
    index: 9,
  },
  "American Samoa": {
    label: "American Samoa",
    name: "American Samoa",
    value: false,
    index: 10,
  },
  Andorra: {
    label: "Andorra",
    name: "Andorra",
    value: false,
    index: 11,
  },
  Angola: {
    label: "Angola",
    name: "Angola",
    value: false,
    index: 12,
  },
  Anguilla: {
    label: "Anguilla",
    name: "Anguilla",
    value: false,
    index: 13,
  },
  Antarctica: {
    label: "Antarctica",
    name: "Antarctica",
    value: false,
    index: 14,
  },
  "Antigua and Barbuda": {
    label: "Antigua and Barbuda",
    name: "Antigua and Barbuda",
    value: false,
    index: 15,
  },
  Argentina: {
    label: "Argentina",
    name: "Argentina",
    value: false,
    index: 16,
  },
  Armenia: {
    label: "Armenia",
    name: "Armenia",
    value: false,
    index: 17,
  },
  Aruba: {
    label: "Aruba",
    name: "Aruba",
    value: false,
    index: 18,
  },
  Australia: {
    label: "Australia",
    name: "Australia",
    value: false,
    index: 19,
  },
  Austria: {
    label: "Austria",
    name: "Austria",
    value: false,
    index: 20,
  },
  Azerbaijan: {
    label: "Azerbaijan",
    name: "Azerbaijan",
    value: false,
    index: 21,
  },
  Bahamas: {
    label: "Bahamas",
    name: "Bahamas",
    value: false,
    index: 22,
  },
  Bahrain: {
    label: "Bahrain",
    name: "Bahrain",
    value: false,
    index: 23,
  },
  Bangladesh: {
    label: "Bangladesh",
    name: "Bangladesh",
    value: false,
    index: 24,
  },
  Barbados: {
    label: "Barbados",
    name: "Barbados",
    value: false,
    index: 25,
  },
  Belarus: {
    label: "Belarus",
    name: "Belarus",
    value: false,
    index: 26,
  },
  Belgium: {
    label: "Belgium",
    name: "Belgium",
    value: false,
    index: 27,
  },
  Belize: {
    label: "Belize",
    name: "Belize",
    value: false,
    index: 28,
  },
  Benin: {
    label: "Benin",
    name: "Benin",
    value: false,
    index: 29,
  },
  Bermuda: {
    label: "Bermuda",
    name: "Bermuda",
    value: false,
    index: 30,
  },
  Bhutan: {
    label: "Bhutan",
    name: "Bhutan",
    value: false,
    index: 31,
  },
  Bolivia: {
    label: "Bolivia",
    name: "Bolivia",
    value: false,
    index: 32,
  },
  Bonaire: {
    label: "Bonaire",
    name: "Bonaire",
    value: false,
    index: 33,
  },
  "Bosnia and Herzegovina": {
    label: "Bosnia and Herzegovina",
    name: "Bosnia and Herzegovina",
    value: false,
    index: 34,
  },
  Botswana: {
    label: "Botswana",
    name: "Botswana",
    value: false,
    index: 35,
  },
  "Bouvet Island": {
    label: "Bouvet Island",
    name: "Bouvet Island",
    value: false,
    index: 36,
  },
  Brazil: {
    label: "Brazil",
    name: "Brazil",
    value: false,
    index: 37,
  },
  "British Indian Ocean Territory": {
    label: "British Indian Ocean Territory",
    name: "British Indian Ocean Territory",
    value: false,
    index: 38,
  },
  "Brunei Darussalam": {
    label: "Brunei Darussalam",
    name: "Brunei Darussalam",
    value: false,
    index: 39,
  },
  Bulgaria: {
    label: "Bulgaria",
    name: "Bulgaria",
    value: false,
    index: 40,
  },
  "Burkina Faso": {
    label: "Burkina Faso",
    name: "Burkina Faso",
    value: false,
    index: 41,
  },
  Burundi: {
    label: "Burundi",
    name: "Burundi",
    value: false,
    index: 42,
  },
  Cambodia: {
    label: "Cambodia",
    name: "Cambodia",
    value: false,
    index: 43,
  },
  Cameroon: {
    label: "Cameroon",
    name: "Cameroon",
    value: false,
    index: 44,
  },
  Canada: {
    label: "Canada",
    name: "Canada",
    value: false,
    index: 45,
  },
  "Cape Verde": {
    label: "Cape Verde",
    name: "Cape Verde",
    value: false,
    index: 46,
  },
  "Cayman Islands": {
    label: "Cayman Islands",
    name: "Cayman Islands",
    value: false,
    index: 47,
  },
  "Central African Republic": {
    label: "Central African Republic",
    name: "Central African Republic",
    value: false,
    index: 48,
  },
  Chad: {
    label: "Chad",
    name: "Chad",
    value: false,
    index: 49,
  },
  Chile: {
    label: "Chile",
    name: "Chile",
    value: false,
    index: 50,
  },
  China: {
    label: "China",
    name: "China",
    value: false,
    index: 51,
  },
  "Christmas Island": {
    label: "Christmas Island",
    name: "Christmas Island",
    value: false,
    index: 52,
  },
  "Cocos (Keeling) Islands": {
    label: "Cocos (Keeling) Islands",
    name: "Cocos (Keeling) Islands",
    value: false,
    index: 53,
  },
  Colombia: {
    label: "Colombia",
    name: "Colombia",
    value: false,
    index: 54,
  },
  Comoros: {
    label: "Comoros",
    name: "Comoros",
    value: false,
    index: 55,
  },
  Congo: {
    label: "Congo",
    name: "Congo",
    value: false,
    index: 56,
  },
  "Congo the Democratic Republic of the": {
    label: "Congo the Democratic Republic of the",
    name: "Congo the Democratic Republic of the",
    value: false,
    index: 57,
  },
  "Cook Islands": {
    label: "Cook Islands",
    name: "Cook Islands",
    value: false,
    index: 58,
  },
  "Costa Rica": {
    label: "Costa Rica",
    name: "Costa Rica",
    value: false,
    index: 59,
  },
  "Cote d'Ivoire": {
    label: "Cote d'Ivoire",
    name: "Cote d'Ivoire",
    value: false,
    index: 60,
  },
  Croatia: {
    label: "Croatia",
    name: "Croatia",
    value: false,
    index: 61,
  },
  Cuba: {
    label: "Cuba",
    name: "Cuba",
    value: false,
    index: 62,
  },
  Curacao: {
    label: "Curacao",
    name: "Curacao",
    value: false,
    index: 63,
  },
  Cyprus: {
    label: "Cyprus",
    name: "Cyprus",
    value: false,
    index: 64,
  },
  "Czech Republic": {
    label: "Czech Republic",
    name: "Czech Republic",
    value: false,
    index: 65,
  },
  Denmark: {
    label: "Denmark",
    name: "Denmark",
    value: false,
    index: 66,
  },
  Djibouti: {
    label: "Djibouti",
    name: "Djibouti",
    value: false,
    index: 67,
  },
  Dominica: {
    label: "Dominica",
    name: "Dominica",
    value: false,
    index: 68,
  },
  "Dominican Republic": {
    label: "Dominican Republic",
    name: "Dominican Republic",
    value: false,
    index: 69,
  },
  Ecuador: {
    label: "Ecuador",
    name: "Ecuador",
    value: false,
    index: 70,
  },
  Egypt: {
    label: "Egypt",
    name: "Egypt",
    value: false,
    index: 71,
  },
  "El Salvador": {
    label: "El Salvador",
    name: "El Salvador",
    value: false,
    index: 72,
  },
  "Equatorial Guinea": {
    label: "Equatorial Guinea",
    name: "Equatorial Guinea",
    value: false,
    index: 73,
  },
  Eritrea: {
    label: "Eritrea",
    name: "Eritrea",
    value: false,
    index: 74,
  },
  Estonia: {
    label: "Estonia",
    name: "Estonia",
    value: false,
    index: 75,
  },
  Ethiopia: {
    label: "Ethiopia",
    name: "Ethiopia",
    value: false,
    index: 76,
  },
  "Falkland Islands (Malvinas)": {
    label: "Falkland Islands (Malvinas)",
    name: "Falkland Islands (Malvinas)",
    value: false,
    index: 77,
  },
  "Faroe Islands": {
    label: "Faroe Islands",
    name: "Faroe Islands",
    value: false,
    index: 78,
  },
  Fiji: {
    label: "Fiji",
    name: "Fiji",
    value: false,
    index: 79,
  },
  Finland: {
    label: "Finland",
    name: "Finland",
    value: false,
    index: 80,
  },
  "French Guiana": {
    label: "French Guiana",
    name: "French Guiana",
    value: false,
    index: 81,
  },
  "French Polynesia": {
    label: "French Polynesia",
    name: "French Polynesia",
    value: false,
    index: 82,
  },
  "French Southern Territories": {
    label: "French Southern Territories",
    name: "French Southern Territories",
    value: false,
    index: 83,
  },
  Gabon: {
    label: "Gabon",
    name: "Gabon",
    value: false,
    index: 84,
  },
  Gambia: {
    label: "Gambia",
    name: "Gambia",
    value: false,
    index: 85,
  },
  Georgia: {
    label: "Georgia",
    name: "Georgia",
    value: false,
    index: 86,
  },
  Ghana: {
    label: "Ghana",
    name: "Ghana",
    value: false,
    index: 87,
  },
  Gibraltar: {
    label: "Gibraltar",
    name: "Gibraltar",
    value: false,
    index: 88,
  },
  Greece: {
    label: "Greece",
    name: "Greece",
    value: false,
    index: 89,
  },
  Greenland: {
    label: "Greenland",
    name: "Greenland",
    value: false,
    index: 90,
  },
  Grenada: {
    label: "Grenada",
    name: "Grenada",
    value: false,
    index: 91,
  },
  Guadeloupe: {
    label: "Guadeloupe",
    name: "Guadeloupe",
    value: false,
    index: 92,
  },
  Guam: {
    label: "Guam",
    name: "Guam",
    value: false,
    index: 93,
  },
  Guatemala: {
    label: "Guatemala",
    name: "Guatemala",
    value: false,
    index: 94,
  },
  Guernsey: {
    label: "Guernsey",
    name: "Guernsey",
    value: false,
    index: 95,
  },
  Guinea: {
    label: "Guinea",
    name: "Guinea",
    value: false,
    index: 96,
  },
  "Guinea-Bissau": {
    label: "Guinea-Bissau",
    name: "Guinea-Bissau",
    value: false,
    index: 97,
  },
  Guyana: {
    label: "Guyana",
    name: "Guyana",
    value: false,
    index: 98,
  },
  Haiti: {
    label: "Haiti",
    name: "Haiti",
    value: false,
    index: 99,
  },
  "Heard Island and McDonald Islands": {
    label: "Heard Island and McDonald Islands",
    name: "Heard Island and McDonald Islands",
    value: false,
    index: 100,
  },
  "Holy See (Vatican City State)": {
    label: "Holy See (Vatican City State)",
    name: "Holy See (Vatican City State)",
    value: false,
    index: 101,
  },
  Honduras: {
    label: "Honduras",
    name: "Honduras",
    value: false,
    index: 102,
  },
  "Hong Kong": {
    label: "Hong Kong",
    name: "Hong Kong",
    value: false,
    index: 103,
  },
  Hungary: {
    label: "Hungary",
    name: "Hungary",
    value: false,
    index: 104,
  },
  Iceland: {
    label: "Iceland",
    name: "Iceland",
    value: false,
    index: 105,
  },
  India: {
    label: "India",
    name: "India",
    value: false,
    index: 106,
  },
  Indonesia: {
    label: "Indonesia",
    name: "Indonesia",
    value: false,
    index: 107,
  },
  Iran: {
    label: "Iran",
    name: "Iran",
    value: false,
    index: 108,
  },
  Iraq: {
    label: "Iraq",
    name: "Iraq",
    value: false,
    index: 109,
  },
  "Isle of Man": {
    label: "Isle of Man",
    name: "Isle of Man",
    value: false,
    index: 110,
  },
  Israel: {
    label: "Israel",
    name: "Israel",
    value: false,
    index: 111,
  },
  Italy: {
    label: "Italy",
    name: "Italy",
    value: false,
    index: 112,
  },
  Jamaica: {
    label: "Jamaica",
    name: "Jamaica",
    value: false,
    index: 113,
  },
  Japan: {
    label: "Japan",
    name: "Japan",
    value: false,
    index: 114,
  },
  Jersey: {
    label: "Jersey",
    name: "Jersey",
    value: false,
    index: 115,
  },
  Jordan: {
    label: "Jordan",
    name: "Jordan",
    value: false,
    index: 116,
  },
  Kazakhstan: {
    label: "Kazakhstan",
    name: "Kazakhstan",
    value: false,
    index: 117,
  },
  Kenya: {
    label: "Kenya",
    name: "Kenya",
    value: false,
    index: 118,
  },
  Kiribati: {
    label: "Kiribati",
    name: "Kiribati",
    value: false,
    index: 119,
  },
  Korea: {
    label: "Korea",
    name: "Korea",
    value: false,
    index: 120,
  },
  Kuwait: {
    label: "Kuwait",
    name: "Kuwait",
    value: false,
    index: 121,
  },
  Kyrgyzstan: {
    label: "Kyrgyzstan",
    name: "Kyrgyzstan",
    value: false,
    index: 122,
  },
  "Lao People's Democratic Republic": {
    label: "Lao People's Democratic Republic",
    name: "Lao People's Democratic Republic",
    value: false,
    index: 123,
  },
  Latvia: {
    label: "Latvia",
    name: "Latvia",
    value: false,
    index: 124,
  },
  Lebanon: {
    label: "Lebanon",
    name: "Lebanon",
    value: false,
    index: 125,
  },
  Lesotho: {
    label: "Lesotho",
    name: "Lesotho",
    value: false,
    index: 126,
  },
  Liberia: {
    label: "Liberia",
    name: "Liberia",
    value: false,
    index: 127,
  },
  Libya: {
    label: "Libya",
    name: "Libya",
    value: false,
    index: 128,
  },
  Liechtenstein: {
    label: "Liechtenstein",
    name: "Liechtenstein",
    value: false,
    index: 129,
  },
  Lithuania: {
    label: "Lithuania",
    name: "Lithuania",
    value: false,
    index: 130,
  },
  Luxembourg: {
    label: "Luxembourg",
    name: "Luxembourg",
    value: false,
    index: 131,
  },
  Macao: {
    label: "Macao",
    name: "Macao",
    value: false,
    index: 132,
  },
  Macedonia: {
    label: "Macedonia",
    name: "Macedonia",
    value: false,
    index: 133,
  },
  Madagascar: {
    label: "Madagascar",
    name: "Madagascar",
    value: false,
    index: 134,
  },
  Malawi: {
    label: "Malawi",
    name: "Malawi",
    value: false,
    index: 135,
  },
  Malaysia: {
    label: "Malaysia",
    name: "Malaysia",
    value: false,
    index: 136,
  },
  Maldives: {
    label: "Maldives",
    name: "Maldives",
    value: false,
    index: 137,
  },
  Mali: {
    label: "Mali",
    name: "Mali",
    value: false,
    index: 138,
  },
  Malta: {
    label: "Malta",
    name: "Malta",
    value: false,
    index: 139,
  },
  "Marshall Islands": {
    label: "Marshall Islands",
    name: "Marshall Islands",
    value: false,
    index: 140,
  },
  Martinique: {
    label: "Martinique",
    name: "Martinique",
    value: false,
    index: 141,
  },
  Mauritania: {
    label: "Mauritania",
    name: "Mauritania",
    value: false,
    index: 142,
  },
  Mauritius: {
    label: "Mauritius",
    name: "Mauritius",
    value: false,
    index: 143,
  },
  Mayotte: {
    label: "Mayotte",
    name: "Mayotte",
    value: false,
    index: 144,
  },
  Mexico: {
    label: "Mexico",
    name: "Mexico",
    value: false,
    index: 145,
  },
  Micronesia: {
    label: "Micronesia",
    name: "Micronesia",
    value: false,
    index: 146,
  },
  Moldova: {
    label: "Moldova",
    name: "Moldova",
    value: false,
    index: 147,
  },
  Monaco: {
    label: "Monaco",
    name: "Monaco",
    value: false,
    index: 148,
  },
  Mongolia: {
    label: "Mongolia",
    name: "Mongolia",
    value: false,
    index: 149,
  },
  Montenegro: {
    label: "Montenegro",
    name: "Montenegro",
    value: false,
    index: 150,
  },
  Montserrat: {
    label: "Montserrat",
    name: "Montserrat",
    value: false,
    index: 151,
  },
  Morocco: {
    label: "Morocco",
    name: "Morocco",
    value: false,
    index: 152,
  },
  Mozambique: {
    label: "Mozambique",
    name: "Mozambique",
    value: false,
    index: 153,
  },
  Myanmar: {
    label: "Myanmar",
    name: "Myanmar",
    value: false,
    index: 154,
  },
  Namibia: {
    label: "Namibia",
    name: "Namibia",
    value: false,
    index: 155,
  },
  Nauru: {
    label: "Nauru",
    name: "Nauru",
    value: false,
    index: 156,
  },
  Nepal: {
    label: "Nepal",
    name: "Nepal",
    value: false,
    index: 157,
  },
  Netherlands: {
    label: "Netherlands",
    name: "Netherlands",
    value: false,
    index: 158,
  },
  "New Caledonia": {
    label: "New Caledonia",
    name: "New Caledonia",
    value: false,
    index: 159,
  },
  "New Zealand": {
    label: "New Zealand",
    name: "New Zealand",
    value: false,
    index: 160,
  },
  Nicaragua: {
    label: "Nicaragua",
    name: "Nicaragua",
    value: false,
    index: 161,
  },
  Niger: {
    label: "Niger",
    name: "Niger",
    value: false,
    index: 162,
  },
  Nigeria: {
    label: "Nigeria",
    name: "Nigeria",
    value: false,
    index: 163,
  },
  Niue: {
    label: "Niue",
    name: "Niue",
    value: false,
    index: 164,
  },
  "Norfolk Island": {
    label: "Norfolk Island",
    name: "Norfolk Island",
    value: false,
    index: 165,
  },
  "Northern Mariana Islands": {
    label: "Northern Mariana Islands",
    name: "Northern Mariana Islands",
    value: false,
    index: 166,
  },
  Norway: {
    label: "Norway",
    name: "Norway",
    value: false,
    index: 167,
  },
  Oman: {
    label: "Oman",
    name: "Oman",
    value: false,
    index: 168,
  },
  Pakistan: {
    label: "Pakistan",
    name: "Pakistan",
    value: false,
    index: 169,
  },
  Palau: {
    label: "Palau",
    name: "Palau",
    value: false,
    index: 170,
  },
  "Palestinian Territory": {
    label: "Palestinian Territory",
    name: "Palestinian Territory",
    value: false,
    index: 171,
  },
  Panama: {
    label: "Panama",
    name: "Panama",
    value: false,
    index: 172,
  },
  "Papua New Guinea": {
    label: "Papua New Guinea",
    name: "Papua New Guinea",
    value: false,
    index: 173,
  },
  Paraguay: {
    label: "Paraguay",
    name: "Paraguay",
    value: false,
    index: 174,
  },
  Peru: {
    label: "Peru",
    name: "Peru",
    value: false,
    index: 175,
  },
  Philippines: {
    label: "Philippines",
    name: "Philippines",
    value: false,
    index: 176,
  },
  Pitcairn: {
    label: "Pitcairn",
    name: "Pitcairn",
    value: false,
    index: 177,
  },
  Poland: {
    label: "Poland",
    name: "Poland",
    value: false,
    index: 178,
  },
  Portugal: {
    label: "Portugal",
    name: "Portugal",
    value: false,
    index: 179,
  },
  "Puerto Rico": {
    label: "Puerto Rico",
    name: "Puerto Rico",
    value: false,
    index: 180,
  },
  Qatar: {
    label: "Qatar",
    name: "Qatar",
    value: false,
    index: 181,
  },
  Reunion: {
    label: "Reunion",
    name: "Reunion",
    value: false,
    index: 182,
  },
  Romania: {
    label: "Romania",
    name: "Romania",
    value: false,
    index: 183,
  },
  "Russian Federation": {
    label: "Russian Federation",
    name: "Russian Federation",
    value: false,
    index: 184,
  },
  Rwanda: {
    label: "Rwanda",
    name: "Rwanda",
    value: false,
    index: 185,
  },
  "Saint Barthelemy": {
    label: "Saint Barthelemy",
    name: "Saint Barthelemy",
    value: false,
    index: 186,
  },
  "Saint Helena": {
    label: "Saint Helena",
    name: "Saint Helena",
    value: false,
    index: 187,
  },
  "Saint Kitts and Nevis": {
    label: "Saint Kitts and Nevis",
    name: "Saint Kitts and Nevis",
    value: false,
    index: 188,
  },
  "Saint Lucia": {
    label: "Saint Lucia",
    name: "Saint Lucia",
    value: false,
    index: 189,
  },
  "Saint Martin (French part)": {
    label: "Saint Martin (French part)",
    name: "Saint Martin (French part)",
    value: false,
    index: 190,
  },
  "Saint Pierre and Miquelon": {
    label: "Saint Pierre and Miquelon",
    name: "Saint Pierre and Miquelon",
    value: false,
    index: 191,
  },
  "Saint Vincent and the Grenadines": {
    label: "Saint Vincent and the Grenadines",
    name: "Saint Vincent and the Grenadines",
    value: false,
    index: 192,
  },
  Samoa: {
    label: "Samoa",
    name: "Samoa",
    value: false,
    index: 193,
  },
  "San Marino": {
    label: "San Marino",
    name: "San Marino",
    value: false,
    index: 194,
  },
  "Sao Tome and Principe": {
    label: "Sao Tome and Principe",
    name: "Sao Tome and Principe",
    value: false,
    index: 195,
  },
  "Saudi Arabia": {
    label: "Saudi Arabia",
    name: "Saudi Arabia",
    value: false,
    index: 196,
  },
  Senegal: {
    label: "Senegal",
    name: "Senegal",
    value: false,
    index: 197,
  },
  Serbia: {
    label: "Serbia",
    name: "Serbia",
    value: false,
    index: 198,
  },
  Seychelles: {
    label: "Seychelles",
    name: "Seychelles",
    value: false,
    index: 199,
  },
  "Sierra Leone": {
    label: "Sierra Leone",
    name: "Sierra Leone",
    value: false,
    index: 200,
  },
  Singapore: {
    label: "Singapore",
    name: "Singapore",
    value: false,
    index: 201,
  },
  "Sint Maarten (Dutch part)": {
    label: "Sint Maarten (Dutch part)",
    name: "Sint Maarten (Dutch part)",
    value: false,
    index: 202,
  },
  Slovakia: {
    label: "Slovakia",
    name: "Slovakia",
    value: false,
    index: 203,
  },
  Slovenia: {
    label: "Slovenia",
    name: "Slovenia",
    value: false,
    index: 204,
  },
  "Solomon Islands": {
    label: "Solomon Islands",
    name: "Solomon Islands",
    value: false,
    index: 205,
  },
  Somalia: {
    label: "Somalia",
    name: "Somalia",
    value: false,
    index: 206,
  },
  "South Africa": {
    label: "South Africa",
    name: "South Africa",
    value: false,
    index: 207,
  },
  "South Georgia and the South Sandwich Islands": {
    label: "South Georgia and the South Sandwich Islands",
    name: "South Georgia and the South Sandwich Islands",
    value: false,
    index: 208,
  },
  "South Sudan": {
    label: "South Sudan",
    name: "South Sudan",
    value: false,
    index: 209,
  },
  "Sri Lanka": {
    label: "Sri Lanka",
    name: "Sri Lanka",
    value: false,
    index: 210,
  },
  Sudan: {
    label: "Sudan",
    name: "Sudan",
    value: false,
    index: 211,
  },
  Suriname: {
    label: "Suriname",
    name: "Suriname",
    value: false,
    index: 212,
  },
  "Svalbard and Jan Mayen": {
    label: "Svalbard and Jan Mayen",
    name: "Svalbard and Jan Mayen",
    value: false,
    index: 213,
  },
  Swaziland: {
    label: "Swaziland",
    name: "Swaziland",
    value: false,
    index: 214,
  },
  Sweden: {
    label: "Sweden",
    name: "Sweden",
    value: false,
    index: 215,
  },
  Switzerland: {
    label: "Switzerland",
    name: "Switzerland",
    value: false,
    index: 216,
  },
  "Syrian Arab Republic": {
    label: "Syrian Arab Republic",
    name: "Syrian Arab Republic",
    value: false,
    index: 217,
  },
  Taiwan: {
    label: "Taiwan",
    name: "Taiwan",
    value: false,
    index: 218,
  },
  Tajikistan: {
    label: "Tajikistan",
    name: "Tajikistan",
    value: false,
    index: 219,
  },
  Tanzania: {
    label: "Tanzania",
    name: "Tanzania",
    value: false,
    index: 220,
  },
  Thailand: {
    label: "Thailand",
    name: "Thailand",
    value: false,
    index: 221,
  },
  "Timor-Leste": {
    label: "Timor-Leste",
    name: "Timor-Leste",
    value: false,
    index: 222,
  },
  Togo: {
    label: "Togo",
    name: "Togo",
    value: false,
    index: 223,
  },
  Tokelau: {
    label: "Tokelau",
    name: "Tokelau",
    value: false,
    index: 224,
  },
  Tonga: {
    label: "Tonga",
    name: "Tonga",
    value: false,
    index: 225,
  },
  "Trinidad and Tobago": {
    label: "Trinidad and Tobago",
    name: "Trinidad and Tobago",
    value: false,
    index: 226,
  },
  Tunisia: {
    label: "Tunisia",
    name: "Tunisia",
    value: false,
    index: 227,
  },
  Turkey: {
    label: "Turkey",
    name: "Turkey",
    value: false,
    index: 228,
  },
  Turkmenistan: {
    label: "Turkmenistan",
    name: "Turkmenistan",
    value: false,
    index: 229,
  },
  "Turks and Caicos Islands": {
    label: "Turks and Caicos Islands",
    name: "Turks and Caicos Islands",
    value: false,
    index: 230,
  },
  Tuvalu: {
    label: "Tuvalu",
    name: "Tuvalu",
    value: false,
    index: 231,
  },
  Uganda: {
    label: "Uganda",
    name: "Uganda",
    value: false,
    index: 232,
  },
  Ukraine: {
    label: "Ukraine",
    name: "Ukraine",
    value: false,
    index: 233,
  },
  "United Arab Emirates": {
    label: "United Arab Emirates",
    name: "United Arab Emirates",
    value: false,
    index: 234,
  },
  "United States Minor Outlying Islands": {
    label: "United States Minor Outlying Islands",
    name: "United States Minor Outlying Islands",
    value: false,
    index: 235,
  },
  Uruguay: {
    label: "Uruguay",
    name: "Uruguay",
    value: false,
    index: 236,
  },
  Uzbekistan: {
    label: "Uzbekistan",
    name: "Uzbekistan",
    value: false,
    index: 237,
  },
  Vanuatu: {
    label: "Vanuatu",
    name: "Vanuatu",
    value: false,
    index: 238,
  },
  "Venezuela, Bolivarian Republic of": {
    label: "Venezuela, Bolivarian Republic of",
    name: "Venezuela, Bolivarian Republic of",
    value: false,
    index: 239,
  },
  Vietnam: {
    label: "Vietnam",
    name: "Vietnam",
    value: false,
    index: 240,
  },
  "Wallis and Futuna": {
    label: "Wallis and Futuna",
    name: "Wallis and Futuna",
    value: false,
    index: 241,
  },
  "Western Sahara": {
    label: "Western Sahara",
    name: "Western Sahara",
    value: false,
    index: 242,
  },
  Yemen: {
    label: "Yemen",
    name: "Yemen",
    value: false,
    index: 243,
  },
  Zambia: {
    label: "Zambia",
    name: "Zambia",
    value: false,
    index: 244,
  },
  Zimbabwe: {
    label: "Zimbabwe",
    name: "Zimbabwe",
    value: false,
    index: 245,
  },
};
