export const DEVICE_COMPATIBILITY = ["mobile", "tablet", "desktop"];

export const LANGUAGE_INDEX_PROLIFIC_MAPPING = {
  Afrikaans: {
    label: "Afrikaans",
    name: "Afrikaans",
    value: false,
    index: 0,
  },
  Albanian: {
    label: "Albanian",
    name: "Albanian",
    value: false,
    index: 1,
  },
  Amharic: {
    label: "Amharic",
    name: "Amharic",
    value: false,
    index: 2,
  },
  Arabic: {
    label: "Arabic",
    name: "Arabic",
    value: false,
    index: 3,
  },
  Armenian: {
    label: "Armenian",
    name: "Armenian",
    value: false,
    index: 4,
  },
  Basque: {
    label: "Basque",
    name: "Basque",
    value: false,
    index: 5,
  },
  Bengali: {
    label: "Bengali",
    name: "Bengali",
    value: false,
    index: 6,
  },
  Belarusian: {
    label: "Belarusian",
    name: "Belarusian",
    value: false,
    index: 7,
  },
  Burmese: {
    label: "Burmese",
    name: "Burmese",
    value: false,
    index: 8,
  },
  Bulgarian: {
    label: "Bulgarian",
    name: "Bulgarian",
    value: false,
    index: 9,
  },
  Catalan: {
    label: "Catalan",
    name: "Catalan",
    value: false,
    index: 10,
  },
  Czech: {
    label: "Czech",
    name: "Czech",
    value: false,
    index: 11,
  },
  Chinese: {
    label: "Chinese",
    name: "Chinese",
    value: false,
    index: 12,
  },
  Croatian: {
    label: "Croatian",
    name: "Croatian",
    value: false,
    index: 13,
  },
  Danish: {
    label: "Danish",
    name: "Danish",
    value: false,
    index: 14,
  },
  Dari: {
    label: "Dari",
    name: "Dari",
    value: false,
    index: 15,
  },
  Dzongkha: {
    label: "Dzongkha",
    name: "Dzongkha",
    value: false,
    index: 16,
  },
  Dutch: {
    label: "Dutch",
    name: "Dutch",
    value: false,
    index: 17,
  },
  English: {
    label: "English",
    name: "English",
    value: false,
    index: 18,
  },
  Esperanto: {
    label: "Esperanto",
    name: "Esperanto",
    value: false,
    index: 19,
  },
  Estonian: {
    label: "Estonian",
    name: "Estonian",
    value: false,
    index: 20,
  },
  Faroese: {
    label: "Faroese",
    name: "Faroese",
    value: false,
    index: 21,
  },
  Farsi: {
    label: "Farsi",
    name: "Farsi",
    value: false,
    index: 22,
  },
  Finnish: {
    label: "Finnish",
    name: "Finnish",
    value: false,
    index: 23,
  },
  French: {
    label: "French",
    name: "French",
    value: false,
    index: 24,
  },
  Gaelic: {
    label: "Gaelic",
    name: "Gaelic",
    value: false,
    index: 25,
  },
  Galician: {
    label: "Galician",
    name: "Galician",
    value: false,
    index: 26,
  },
  German: {
    label: "German",
    name: "German",
    value: false,
    index: 27,
  },
  Greek: {
    label: "Greek",
    name: "Greek",
    value: false,
    index: 28,
  },
  Hebrew: {
    label: "Hebrew",
    name: "Hebrew",
    value: false,
    index: 29,
  },
  Hindi: {
    label: "Hindi",
    name: "Hindi",
    value: false,
    index: 30,
  },
  Hungarian: {
    label: "Hungarian",
    name: "Hungarian",
    value: false,
    index: 31,
  },
  Icelandic: {
    label: "Icelandic",
    name: "Icelandic",
    value: false,
    index: 32,
  },
  Indonesian: {
    label: "Indonesian",
    name: "Indonesian",
    value: false,
    index: 33,
  },
  Inuktitut: {
    label: "Inuktitut",
    name: "Inuktitut",
    value: false,
    index: 34,
  },
  Italian: {
    label: "Italian",
    name: "Italian",
    value: false,
    index: 35,
  },
  Japanese: {
    label: "Japanese",
    name: "Japanese",
    value: false,
    index: 36,
  },
  Khmer: {
    label: "Khmer",
    name: "Khmer",
    value: false,
    index: 37,
  },
  Korean: {
    label: "Korean",
    name: "Korean",
    value: false,
    index: 38,
  },
  Kurdish: {
    label: "Kurdish",
    name: "Kurdish",
    value: false,
    index: 39,
  },
  Laotian: {
    label: "Laotian",
    name: "Laotian",
    value: false,
    index: 40,
  },
  Latvian: {
    label: "Latvian",
    name: "Latvian",
    value: false,
    index: 41,
  },
  Lappish: {
    label: "Lappish",
    name: "Lappish",
    value: false,
    index: 42,
  },
  Lithuanian: {
    label: "Lithuanian",
    name: "Lithuanian",
    value: false,
    index: 43,
  },
  Macedonian: {
    label: "Macedonian",
    name: "Macedonian",
    value: false,
    index: 44,
  },
  Malay: {
    label: "Malay",
    name: "Malay",
    value: false,
    index: 45,
  },
  Maltese: {
    label: "Maltese",
    name: "Maltese",
    value: false,
    index: 46,
  },
  Nepali: {
    label: "Nepali",
    name: "Nepali",
    value: false,
    index: 47,
  },
  Norwegian: {
    label: "Norwegian",
    name: "Norwegian",
    value: false,
    index: 48,
  },
  Pashto: {
    label: "Pashto",
    name: "Pashto",
    value: false,
    index: 49,
  },
  Polish: {
    label: "Polish",
    name: "Polish",
    value: false,
    index: 50,
  },
  Portuguese: {
    label: "Portuguese",
    name: "Portuguese",
    value: false,
    index: 51,
  },
  Romanian: {
    label: "Romanian",
    name: "Romanian",
    value: false,
    index: 52,
  },
  Russian: {
    label: "Russian",
    name: "Russian",
    value: false,
    index: 53,
  },
  Scots: {
    label: "Scots",
    name: "Scots",
    value: false,
    index: 54,
  },
  Serbian: {
    label: "Serbian",
    name: "Serbian",
    value: false,
    index: 55,
  },
  Slovak: {
    label: "Slovak",
    name: "Slovak",
    value: false,
    index: 56,
  },
  Slovenian: {
    label: "Slovenian",
    name: "Slovenian",
    value: false,
    index: 57,
  },
  Somali: {
    label: "Somali",
    name: "Somali",
    value: false,
    index: 58,
  },
  Spanish: {
    label: "Spanish",
    name: "Spanish",
    value: false,
    index: 59,
  },
  Swedish: {
    label: "Swedish",
    name: "Swedish",
    value: false,
    index: 60,
  },
  Swahili: {
    label: "Swahili",
    name: "Swahili",
    value: false,
    index: 61,
  },
  "Tagalog-Filipino": {
    label: "Tagalog-Filipino",
    name: "Tagalog-Filipino",
    value: false,
    index: 62,
  },
  Tajik: {
    label: "Tajik",
    name: "Tajik",
    value: false,
    index: 63,
  },
  Tamil: {
    label: "Tamil",
    name: "Tamil",
    value: false,
    index: 64,
  },
  Thai: {
    label: "Thai",
    name: "Thai",
    value: false,
    index: 65,
  },
  Tibetan: {
    label: "Tibetan",
    name: "Tibetan",
    value: false,
    index: 66,
  },
  Tigrinya: {
    label: "Tigrinya",
    name: "Tigrinya",
    value: false,
    index: 67,
  },
  Tongan: {
    label: "Tongan",
    name: "Tongan",
    value: false,
    index: 68,
  },
  Turkish: {
    label: "Turkish",
    name: "Turkish",
    value: false,
    index: 69,
  },
  Turkmen: {
    label: "Turkmen",
    name: "Turkmen",
    value: false,
    index: 70,
  },
  Ukrainian: {
    label: "Ukrainian",
    name: "Ukrainian",
    value: false,
    index: 71,
  },
  Urdu: {
    label: "Urdu",
    name: "Urdu",
    value: false,
    index: 72,
  },
  Uzbek: {
    label: "Uzbek",
    name: "Uzbek",
    value: false,
    index: 73,
  },
  Welsh: {
    label: "Welsh",
    name: "Welsh",
    value: false,
    index: 74,
  },
  Vietnamese: {
    label: "Vietnamese",
    name: "Vietnamese",
    value: false,
    index: 75,
  },
  Telugu: {
    label: "Telugu",
    name: "Telugu",
    value: false,
    index: 76,
  },
  Papiamento: {
    label: "Papiamento",
    name: "Papiamento",
    value: false,
    index: 77,
  },
  Twi: {
    label: "Twi",
    name: "Twi",
    value: false,
    index: 78,
  },
  Cantonese: {
    label: "Cantonese",
    name: "Cantonese",
    value: false,
    index: 79,
  },
  Mandarin: {
    label: "Mandarin",
    name: "Mandarin",
    value: false,
    index: 80,
  },
  Hakka: {
    label: "Hakka",
    name: "Hakka",
    value: false,
    index: 81,
  },
  Malayalam: {
    label: "Malayalam",
    name: "Malayalam",
    value: false,
    index: 82,
  },
  Gujarati: {
    label: "Gujarati",
    name: "Gujarati",
    value: false,
    index: 83,
  },
  Punjabi: {
    label: "Punjabi",
    name: "Punjabi",
    value: false,
    index: 84,
  },
  Georgian: {
    label: "Georgian",
    name: "Georgian",
    value: false,
    index: 85,
  },
  Other: {
    label: "Other",
    name: "Other",
    value: false,
    index: 86,
  },
};
